### ISSUE TITLE
deck card link is show as {object} 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1025]
Browser:
![image](https://user-images.githubusercontent.com/24530680/108824820-77444480-75c2-11eb-9687-72b4597cfed8.png)

App:
![image](https://user-images.githubusercontent.com/24530680/108824935-a3f85c00-75c2-11eb-8d04-d09c5a466cc4.png)

**Comment by mahibi** [comment]
@nickvergessen whats the priority for this?

**Comment by nickvergessen** [comment]
Let's talk about it tomorrow

**Comment by DJPlaya** [comment]
Hi, i got the same issue with Nextcloud Hub 3 (25.0.6) running on Linux 6.1.21-v8+ aarch64 (RPi 4) using module version 15.0.5.
The Talk app is 16.0.1, and the issue happens on at least 2 different Devices (Android 12+).
Am ime missing something important, the bug should be fixed in the version ime running?

**Comment by mahibi** [comment]
can reproduce. happens again..

**Comment by pmarini-nc** [comment]
Hello, still happening on v19.0.1. Any hint on a possible fix timeline? Thanks!
