### ISSUE TITLE
app takes up too much storage space on device

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/talk-android#1405]
## Steps to reproduce
1. install/use talk android app
2. takes up a lot of space (8GB for me, others have reported 11GB). Also after a fresh install on the device.

### Expected behaviour
It should be max 2GB. Maybe give user some control over how much the app can use locally. 

### Actual behaviour
see above

### Comments
This is pretty serious, a lot of people are always close to their storage capacity limit. So even telling them that the app uses 1GB could lead to them not installing it. But 7 GB is wild.
This started as a discussion on the forum https://help.nextcloud.com/t/talk-android-app-taking-up-too-much-space/116562

## Device information

**Device:** Sony XPeria

**Android version:** 8.0.0

**Talk version:** 11.1.0

## Server information

**Nextcloud version:** 20.0.4

**Talk version:**  10.0.8

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by mahibi** [comment]
this is fixed with https://github.com/nextcloud/talk-android/pull/1377
It is available with version 12.1.0 which will be out soon.
The reason was that the log was flooded when certain conditions were met. You might have to clear the cache once you installed the new version.

**Comment by alexanderdd** [comment]
Hello, I have v12.1.1 now, but it still takes up almost 8GB.

**Comment by mahibi** [comment]
did you already try to deinstall and install it again?

**Comment by alexanderdd** [comment]
Ok that solved it :smile: 

There is still a problem: All the users that have it installed don't know that they have to reinstall it. Should I open a separate issue for this or do we track it here?

**Comment by mahibi** [comment]
well i hope not so many users are affected.
this only happened when there was a high performance backend involved AND the user had the phone disconnected from internet for a long time. Only then the logfile is becoming larger and larger.

so i hope if a user is affected he will reinstall it on his own or he will find this issue for the hint...
