### ISSUE TITLE
Duplicate display of messages after screen rotation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#2171]
## Steps to reproduce

1. Open a conversation.
2. Turn the smartphone over to a horizontal position.
3. Turn the smartphone vertical position.
4. Send a message.

Displays of sent messages are duplicated:

![obraz](https://user-images.githubusercontent.com/47037905/176176891-840396e9-61aa-47e3-b790-763b3e231e58.png)

After turning the smartphone over again and back, the re-sent message is double duplicated, etc.:

![obraz](https://user-images.githubusercontent.com/47037905/176177261-46be3ee5-49d4-47ad-8a54-e6d361516b97.png)

## Device information

**Android version:** 10

**Talk version:** 14.1.0 Alpha 11

**Comment by AndyScherzinger** [comment]
@andyxheli @Valdnet what server versions/Talk versions are you running? I have 24 latest and Android Talk client 14.1.0 Alpha 11 and it works fine for me.

**Comment by andyxheli** [comment]
@AndyScherzinger I'm running NC 24.0.2 & Talk 14.0.2

**Comment by andyxheli** [comment]
@AndyScherzinger Please see recording

https://user-images.githubusercontent.com/59488153/176283369-97aa221a-8ccb-4905-bcc4-6a61ec57bc09.mp4

**Comment by AndyScherzinger** [comment]
It is not that I don't or haven't believed you, it is just that I can't reproduce it. @mahibi did you ever experience this or can you reproduce it?

**Comment by andyxheli** [comment]
Thanks Andy! No I didn't even think of that I just wanted to show you. Sorry if it come out that way. I remember a while back the android talk did double text but it was fixed.

**Comment by AndyScherzinger** [comment]
All good @andyxheli 👍 Let'S see if @mahibi has some infos on it.

**Comment by Valdnet** [comment]
> what server versions/Talk versions are you running?

I also use NC 24.0.2 and Talk 14.0.2.

**Comment by mahibi** [comment]
> @mahibi I would also pay attention to this issue #2167. Perhaps it is also related to this.

that's unlikely but will have an eye on it

**Comment by Valdnet** [comment]
@mahibi In version 20.0.5 there is still a problem with displaying sent messages after rotating the smartphone.

**Comment by mahibi** [comment]
> [@mahibi](https://github.com/mahibi) In version 20.0.5 there is still a problem with displaying sent messages after rotating the smartphone.

confirmed, thanks to report it. I have bigger plan to change the chat activity and will keep an eye on this issue!

**Comment by mahibi** [comment]
fixed with https://github.com/nextcloud/talk-android/pull/4641

**Comment by migulen** [comment]
@mahibi, I think it's not totally resolved on v21.0.0-RC1. It's happening, not so many often, but happens, and the new problem it's the messages, got saved on the server an local DB. I will confirm it.

**Comment by mahibi** [comment]
> [@mahibi](https://github.com/mahibi), I think it's not totally resolved on v21.0.0-RC1. It's happening, not so many often, but happens, and the new problem it's the messages, got saved on the server an local DB. I will confirm it.

@migulen thanks to let me know! I experienced one time that messages were duplicated after being sent from android when internet connection was bad. This is a different cause (caused by the retry approach for sending).
Can you confirm this happened when you sent them from phone? Which internet connection was used? Good Wifi? mobile internet?

**Comment by migulen** [comment]
@mahibi , 

- It was without rotation at that time.

- It happens with bad mobile connection.  When trying to send the messages,  the messages appear with the clock like "waiting to be sent". The duplicated messages appeared (viewed) after get out of the room and returning to it. 

- The duplicated messages are seen on the mobile with Nextcloud Talk Android and on a PC with the Firefox browser, so they are really saved on the server DB for sure.

It's some problem about sending the messages twice to the server from the Nextcloud Tall Android APP.

**Comment by mahibi** [comment]
thanks migulen,
as said this bug is about the retry approach for sending when server response is not received to confirm messages are received. I will do some research whats the best way to avoid it.

**Comment by migulen** [comment]
@mahibi , can you show me, less or more, where it's the "retry approach for sending when server response is not received" ?

How much will be the cost of adding an real checksum for each "message content" ?

**"referenceId" is some type of checksum of the message sending action, but, it's always the same checksum for "the same message object/message content (text) , but sent on different time ?"

 I think it isn't. Could be ?**   

-------------------------------
**file "MessageInputViewModel.kt":**

    @Suppress("LongParameterList")
    fun sendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean
    ) {
        **val referenceId = SendMessageUtils().generateReferenceId()**
        Log.d(TAG, "Random SHA-256 Hash: $referenceId")

        viewModelScope.launch {
            chatRepository.addTemporaryMessage(
                message,
                displayName,
                replyTo,
                sendWithoutNotification,
                referenceId
            ).collect { result ->
                if (result.isSuccess) {
                    Log.d(TAG, "temp message ref id: " + (result.getOrNull()?.referenceId ?: "none"))

                    _sendChatMessageViewState.value = SendChatMessageSuccessState(message)
                } else {
                    _sendChatMessageViewState.value = SendChatMessageErrorState(message)
                }
            }
        }

---------------------------
**file "SendMessageUtils.kt":**

class SendMessageUtils {
    **fun generateReferenceId(): String {**
        val randomString = UUID.randomUUID().toString()
        val digest = MessageDigest.getInstance("SHA-256")
        val hashBytes = digest.digest(randomString.toByteArray(Charsets.UTF_8))
        return hashBytes.joinToString("") { "%02x".format(it) }
    }

--------------------------
**file "ChatMessageRepository.kt"**

    @Suppress("LongParameterList")
    suspend fun sendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String
    ): Flow<Result<ChatMessage?>>

    @Suppress("LongParameterList")
    suspend fun resendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String
    ): Flow<Result<ChatMessage?>>

--------------------------
**file "OfflineFirstChatRepository.kt":**


       // remove temp messages from DB that are now found in the new messages
        val chatMessagesReferenceIds = receivedChatMessages.mapTo(HashSet(receivedChatMessages.size)) { it.referenceId }
        val tempChatMessagesThatCanBeReplaced = oldTempMessages.filter { it.referenceId in chatMessagesReferenceIds }
        chatDao.deleteTempChatMessages(
            internalConversationId,
            tempChatMessagesThatCanBeReplaced.map { it.referenceId!! }
        )

----------------------------
**file "OfflineFirstChatRepository.kt":**

   @Suppress("LongParameterList")
    override suspend fun resendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String
    ): Flow<Result<ChatMessage?>> {
        val messageToResend = chatDao.getTempMessageForConversation(internalConversationId, referenceId).first()
        messageToResend.sendingFailed = false
        chatDao.updateChatMessage(messageToResend)

        val messageToResendModel = messageToResend.asModel()
        _updateMessageFlow.emit(messageToResendModel)

        return sendChatMessage(
            credentials,
            url,
            message,
            displayName,
            replyTo,
            sendWithoutNotification,
            referenceId
        )
    }

=====================

**Or, by other way... 

Could be my Spreed DB don't have the "referenceId" colum because it's "v18.0.11" of nextcloud server "v28.0.11" and this is the principal of the problem???

Since when it's implemented "referenceId" on Nextcloud Talk Android APP and Spreed (server) ? 

I've seen this on file "Migrations.kt".**

    fun addTempMessagesSupport(db: SupportSQLiteDatabase) {
        try {
            db.execSQL(
                "ALTER TABLE ChatMessages " +
                    "ADD COLUMN referenceId TEXT;"
            )
        } catch (e: SQLException) {
            Log.i("Migrations", "Something went wrong when adding column referenceId to table ChatMessages")
        }

        try {
            db.execSQL(
                "ALTER TABLE ChatMessages " +
                    "ADD COLUMN isTemporary INTEGER NOT NULL DEFAULT 0;"
            )
        } catch (e: SQLException) {
            Log.i("Migrations", "Something went wrong when adding column isTemporary to table ChatMessages")
        }

=====================


Hope it helps.

**Comment by migulen** [comment]
**@mahibi , can you show me, less or more, where it's the "retry approach for sending when server response is not received" ?**

**How much will be the cost of adding an real checksum for each "full message content" ?**

**"referenceId" is some type of checksum of the message sending action, but, it's always the same checksum for "the same message object/message content (text) , but sent on different time ?"**

 **I think it isn't. Could be ?**   

-------------------------------
**file "MessageInputViewModel.kt":**

    @Suppress("LongParameterList")
    fun sendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean
    ) {
        val referenceId = SendMessageUtils().generateReferenceId()    <<<<< HERE
        Log.d(TAG, "Random SHA-256 Hash: $referenceId")

        viewModelScope.launch {
            chatRepository.addTemporaryMessage(
                message,
                displayName,
                replyTo,
                sendWithoutNotification,
                referenceId
            ).collect { result ->
                if (result.isSuccess) {
                    Log.d(TAG, "temp message ref id: " + (result.getOrNull()?.referenceId ?: "none"))

                    _sendChatMessageViewState.value = SendChatMessageSuccessState(message)
                } else {
                    _sendChatMessageViewState.value = SendChatMessageErrorState(message)
                }
            }
        }

---------------------------
**file "SendMessageUtils.kt":**

   class SendMessageUtils {
         fun generateReferenceId(): String {                          <<<<<< ALL THIS FUNCTION
         val randomString = UUID.randomUUID().toString()             
         val digest = MessageDigest.getInstance("SHA-256")
         val hashBytes = digest.digest(randomString.toByteArray(Charsets.UTF_8))             
         return hashBytes.joinToString("") { "%02x".format(it) }                                            
     }

--------------------------
**file "ChatMessageRepository.kt"**

    @Suppress("LongParameterList")
    suspend fun sendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String                                          <<<<< HERE
    ): Flow<Result<ChatMessage?>>

    @Suppress("LongParameterList")
    suspend fun resendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String                                                 <<<<< HERE
    ): Flow<Result<ChatMessage?>>

--------------------------
**file "OfflineFirstChatRepository.kt":**


       // remove temp messages from DB that are now found in the new messages
        val chatMessagesReferenceIds = receivedChatMessages.mapTo(HashSet(receivedChatMessages.size)) { it.referenceId }   <<<<< HERE
        val tempChatMessagesThatCanBeReplaced = oldTempMessages.filter { it.referenceId in chatMessagesReferenceIds }
        chatDao.deleteTempChatMessages(
            internalConversationId,
            tempChatMessagesThatCanBeReplaced.map { it.referenceId!! }               <<<<< HERE
        )

----------------------------
**file "OfflineFirstChatRepository.kt":**

   @Suppress("LongParameterList")
    override suspend fun resendChatMessage(
        credentials: String,
        url: String,
        message: String,
        displayName: String,
        replyTo: Int,
        sendWithoutNotification: Boolean,
        referenceId: String
    ): Flow<Result<ChatMessage?>> {
        val messageToResend = chatDao.getTempMessageForConversation(internalConversationId, referenceId).first()
        messageToResend.sendingFailed = false
        chatDao.updateChatMessage(messageToResend)

        val messageToResendModel = messageToResend.asModel()
        _updateMessageFlow.emit(messageToResendModel)

        return sendChatMessage(
            credentials,
            url,
            message,
            displayName,
            replyTo,
            sendWithoutNotification,
            referenceId
        )
    }

=====================

**Or, by other way...**

**Could be my Spreed DB don't have the "referenceId" colum because it's "v18.0.11" of nextcloud server "v28.0.11" and this is the principal of the problem???**

**Since when it's implemented "referenceId" on Nextcloud Talk Android APP and Spreed (server) ?**

**I've seen this on file "Migrations.kt".**

    fun addTempMessagesSupport(db: SupportSQLiteDatabase) {
        try {
            db.execSQL(
                "ALTER TABLE ChatMessages " +
                    "ADD COLUMN referenceId TEXT;"
            )
        } catch (e: SQLException) {
            Log.i("Migrations", "Something went wrong when adding column referenceId to table ChatMessages")
        }

        try {
            db.execSQL(
                "ALTER TABLE ChatMessages " +
                    "ADD COLUMN isTemporary INTEGER NOT NULL DEFAULT 0;"
            )
        } catch (e: SQLException) {
            Log.i("Migrations", "Something went wrong when adding column isTemporary to table ChatMessages")
        }

=====================

I don't know if I'm understanding well what it the function of  "generateReferenceId", "referenceId".

Hope it helps.

**Comment by mahibi** [comment]
referenceId is used to identify messages.
They are created on the device even when being offline. After sending, the messages are then retrieved from server. At this point, referenceIds from temporary messages and received messages from server are compared. All temporary messages that match a referenceId from the received messages are deleted. 
This is not suitable to avoid the duplicated messages as server will accept messages with the same referenceId.

The retry-problem that is causing the duplicated messages is this:
https://github.com/nextcloud/talk-android/blob/3330fc82108655b9f13e5e52300e80c87f2f844c/app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt#L842-L849

I will have a closer look at it next week. If i can't find a better handling, the retry part may be removed for the final version for now.

**Comment by migulen** [comment]
> This is not suitable to avoid the duplicated messages as **server will accept messages with the same referenceId**.

That's the "answer". It's not a checksum of the content of the message, but a checksum of the sendind.

 I didn't check if there was some validation of "referenceId" on the server. Sorry, my error. 

------------------------

Well, could be in the future some "integrity (checksum) of the content of the messages" could be implemented on the server side. ;-) . 

I think i've been seen something like that when I send some "repeated emails" by error (same content, same destinations, and very short time gap between them). Only one it's really sent.

**Comment by mahibi** [comment]
There won't be a solution on server side in the near future ("too many database queries required..").
So for now i removed the retry in talk android.. https://github.com/nextcloud/talk-android/pull/4688
