### ISSUE TITLE
Accounts disappear (+notifications are still delivered)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2446]
### Steps to reproduce

see below

### Expected behaviour

see both servers

### Actual behaviour

After updating from RC2 one of my two servers is gone, the account is away but I get notifications for this account. Reinstalling and adding my 2 servers does not solve it

### Device brand and model

Pixel 4a

### Android version

12

### Nextcloud Talk app version

15.0.0-rc.1

**Comment by mahibi** [comment]
you mean after "Reinstalling and adding my 2 servers" while using 15.0.0 RC3 the missing server still not appears in the account switcher and it's conversations are not shown, but notifications still arrive?

**Comment by jakobroehrl** [comment]
Exactly.

**Comment by mahibi** [comment]
can't reproduce yet.
can you maybe try to reproduce this? so installing the old version you had before (i guess it was RC1 ?) and try the same again?
if you can reproduce it would be great to have test accounts for your servers if you're okay with that.

**Comment by jakobroehrl** [comment]
added a third server, now I see all.
I hope it was a hiccup only on my side

**Comment by mahibi** [comment]
thanks for testing @jakobroehrl

**Comment by migulen** [comment]
Hi @jakobroehrl  and @mahibi , it continues happening, but I think that it's related to our specific environment. I've X nextcloud's servers running like VM behind a apache running like reverse proxy.

**Steps to reproduce**

Not always happens at the same moment, i don't catch the correct way to reproduce. I've seen this issue in Talk-Android since v14.2.0-RC1 passing through all the RC until v15.0.0-RC3 (included). In v14.1.1 and v14.1.0 (and previous) didn't happen.

In my case it happens exactly with 2 configured accounts (same username), but on 2 virtual servers running his nextcloud instance each. The apache reverse proxy it's manager that routes the specific request to each server... and I think that it's doing ok.

I've the feeling that it happens more easily when you are doing something like changing between accounts and you "lost the connection" to the server. Or when you are sharing something from other apps (like gallery) to nextcloud talk.

**Expected behaviour**

All configured accounts always available.

**Actual behaviour**

One of the account "eats" the another one. Well not eat, it puts "before/first than" the other account and **hiddes it.**

When you "delete" the visible account, the hidden one comes to "light" (to be visible) in the app.

**Device brand and model**

Xiaomi Mi 9

**Android version**

12

**Nextcloud Talk app version**

14.2.0-RC1 to 15.0.0-RC3.

**Nextcloud server version**

23.0.8

**Talk version**

13.0.8

**Custom Signaling server configured**

No response

**Custom TURN server configured**

Yes

**Custom STUN server configured**

Yes

**Android logs**

No response

**Server log**

No response

**Additional information**

No response

**Comment by migulen** [comment]
@jakobroehrl :

- your accounts have the "same username" ? 
- The accounts are in the same server ?  
- The servers "share the same public ip (reverse-proxied)" or "have different ip each one"?

**Comment by migulen** [comment]
Another thing, that make me suspect that it's something wrong "written"/confusing in the configuration file at nextcloud-talk "android data app", is that if you try to import the hidden account from the "nextcloud android client" (app for files), the hidden one nor the visible one aren't shown to import to the "nextcloud talk-android app".   When you "delete" the visible one on nextcloud talk-android app, then you can choose this account to re-add it to nextcloud-talk app from the "nextcloud android client"*

*Well it's possible if you have all these accounts configured on the "nextcloud android client" (files).

**Comment by jakobroehrl** [comment]
> @jakobroehrl :
> 
>     * your accounts have the "same username" ?
> 
>     * The accounts are in the same server ?
> 
>     * The servers "share the same public ip (reverse-proxied)" or "have different ip each one"?

no, no, different ip

**Comment by migulen** [comment]
@jakobroehrl, so, it seems it could happen with any scenario. It continues happening to me.

**@mahibi, must @jakobroehrl, or I, reopen an issue about this ?**

**Comment by jakobroehrl** [comment]
Today the problem occurs again.
There is probably a litte bug

**Comment by mahibi** [comment]
@migulen always feel free to reopen issues if you think something is not solved.

> I've seen this issue in Talk-Android since v14.2.0-RC1 passing through all the RC until v15.0.0-RC3 (included). In v14.1.1 and v14.1.0 (and previous) didn't happen.

this is actually a very useful info, thank you @migulen :+1: 
So i guess it's maybe the migration from requery to room, since v14.2.0-RC1 contained these changes
https://github.com/nextcloud/talk-android/milestone/57?closed=1

fyi @AndyScherzinger

**Comment by mahibi** [comment]
@jakobroehrl do you also see this behaviour reported by @migulen:
> When you "delete" the visible account, the hidden one comes to "light" (to be visible) in the app.

?

Could you maybe create test accounts for me on your server so i can try to reproduce this @jakobroehrl ?

**Comment by mahibi** [comment]
@migulen ah i was not aware it's not possible to reopen. jakob was able to reopen because he closed it.. 

> I'm now trying v15.0.0-RC4, i will report if it happens with this version.

i'm pretty sure it happens also with this version as nothing was fixed regarding this issue..

> I've the feeling that it happens more easily when you are doing something like changing between accounts (....) Or when you are sharing something from other apps (like gallery) to nextcloud talk.

can you confirm this behaviour @jakobroehrl ?

**Comment by mahibi** [comment]
maybe related: https://github.com/nextcloud/talk-android/issues/2218

**Comment by mahibi** [comment]
@jakobroehrl @migulen 
How often can you reproduce these issues?
If you are willing to create test accounts for me on your servers please send url and credentials to 
marcel . hibbe at nextcloud . com

**Comment by migulen** [comment]
> @jakobroehrl do you also see this behaviour reported by @migulen:
> 
> > When you "delete" the visible account, the hidden one comes to "light" (to be visible) in the app.
> 
> ?
> 
> Could you maybe create test accounts for me on your server so i can try to reproduce this @jakobroehrl ?

When an account get "hidden", you can see if it's configured in nextcloud-tak, but hidden, doing this: 

1.- **Open Nextcloud-talk/Add account/Import account from the Nextcloud app**   <---    Remember that must have configured the accounts on "Nextcloud app" before.

2.- **You can not import from here because "it's not listed".**   <---  The already imported/configured (hidden too) accounts on nextcloud-talk are not shown/listed on this import function.

After that you go to:

3.- (Account Selector or User settings)/Settings/Remove account     <------ The visible account gets deleted and the hidden one, instantly, gets shown and selected. 

4.- Repeat 1.- and you can import the just before deleted account and , after that"normally", the 2 accounts gets correctly configured and visible in nextcloud-talk... until it happens another time "for not clear reasons".

**Comment by migulen** [comment]
> @jakobroehrl @migulen How often can you reproduce these issues? If you are willing to create test accounts for me on your servers please send url and credentials to marcel . hibbe at nextcloud . com

It depends in the use of the app. Normally it happens when you use it more. I could have this problem 2 times a day if I use a lot, the days I don't use or use only few times, it's perfectly possible it don't happen. 

There is some index on the account selector ? It seems it gets overlapped or something.

@mahibi  I'll try to create you an account this night.

**Comment by migulen** [comment]
> maybe related: #2218

Yes... could be. Not so serious bug like this one... but really annoying one. I'm not sure all the notifications arrive to the hidden account. 

Two things to remember: 

- it starts to happen to me from v14.2.0-RC1 until now  (v14.1.0 works ok).

- It happens with 2 accounts (same username) in different instance nextcloud server but same ip reverse-proxied. (@migulen )
- it happens with 2 accounts (different username) in different instance server server with different ip. (@jakobroehrl )

**Comment by AndyScherzinger** [comment]
> When you "delete" the visible account, the hidden one comes to "light" (to be visible) in the app.

@mahibi not sure if a db migration went wrong, I rather don't think so because if deleting accounts, data and app with a reinstall lead to the same behavior I would suspect something with the db queries then. But that might be hard to find except it can be reproduced but a Dev, so they can debug it.

**Comment by migulen** [comment]
> > When you "delete" the visible account, the hidden one comes to "light" (to be visible) in the app.
> 
> @mahibi not sure if a db migration went wrong, I rather don't think so because if deleting accounts, data and app with a reinstall lead to the same behavior I would suspect something with the db queries then. But that might be hard to find except it can be reproduced but a Dev, so they can debug it.

For confirming this issue wasn't related to an upgrade problem between versions of the app (v14.2.0-RC1 until v15.0.0-RC3) (sometimes)  I clear all data from "nextcloud-talk android app" (wipe the data cache and user data from the app),  and then uninstall the app. After, I do fresh install of "nextcloud-talk android app" from github .apk package, and configure my usual accounts at the "nextcloud-talk android app" (importing these accounts from de "nextcloud android app") but I have the same results... before or later, one of the accounts gets hidden on "nextcloud-talk android app". The hidden account could be any of the two configured, I haven't seen a pattern between them (order, server, etc...).

@AndyScherzinger, the times i don't make a "fresh install",  I always check the accounts after upgrading versions of the app, and I never saw any account get hidden in the process. So, it seems to me, that it isn't a a migration problem... but I'm a neophyte.

**Comment by AndyScherzinger** [comment]
Thanks for the details @migulen - does the hiding happen instantly or after some time? Also very important point you mentioned is that it is imported accounts, not accounts that get added via the usual web login flow. also cc @mahibi

**Comment by migulen** [comment]
@AndyScherzinger 

> Thanks for the details @migulen - does the hiding happen instantly or after some time?

[https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1276241805](https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1276241805)

**It depends more on use of the app (or some special action/situation/triggers), than for time count.**

> Also very important point you mentioned is that it is imported accounts, not accounts that get added via the usual web login flow. also cc @mahibi

[https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1265882897](https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1265882897)

**Yes, I pointed it before, normally I import the accounts from "nextcloud (client) android app",  but not always ;-) .** I don't think it's related to be imported from there. Next time hiding happens, I will try to log on "nextcloud-talk android app" using manual way.

**Comment by migulen** [comment]
@AndyScherzinger,

less or more, this is the list of "hiding" events of one of my accounts:

![imagen](https://user-images.githubusercontent.com/60242624/195728182-87e9963c-99e0-4948-bec5-25360f7e6d18.png)

The same situations for the other account.

**Yesterday I upgraded my nextcloud server to v23.0.10, Spreed (Talk) to v13.0.9. Today I've been using v15.0.0-RC4 nextcloud-talk and "account hiding" didn't happened.**

I upgraded to v15.0.0-RC5 to just now... and will continue testing tomorrow.

**Comment by AndyScherzinger** [comment]
@migulen Thanks for the update on infos and findings 🙏

**Comment by mahibi** [comment]
thanks @migulen 
i plan to have a closer look in the evening.

tbh i wonder how import account from files app can work for you. i had a short look today and I had the impression it's broken :D

however one info from @jakobroehrl would be interesting: did you also import the accounts from the files app?

**Comment by migulen** [comment]
>tbh i wonder how import account from files app can work for you. i had a short look today and I had the impression it's broken :D

Ough.... broken ??? It (seems) works perfectly for me :-P.  Which version it's supposed to be broken ? I don't remember if import account works in nextcloud talk v14.x.x, but I think so.

**Comment by mahibi** [comment]
> Ough.... broken ??? It (seems) works perfectly for me :-P. Which version it's supposed to be broken ? I don't remember if import account works in nextcloud talk v14.x.x, but I think so.

just tested with nc android talk v14.0.0 and import option was shown and worked correctly.
with broken i mean that current versions don't even show the option to import accounts. But apparently this is not the case for all devices(?)/scenarios(?)/..? as it works for you..

**Comment by mahibi** [comment]
just checked: it's not related to versions! it only works when apk is manually installed from github. via play store it fails. will have a closer look on monday..

**Comment by migulen** [comment]
> just checked: the hidden "import account from nextcloud app" option is not related to versions! it only works when apk is manually installed from github. via play store it fails. will have a closer look on monday..

**@mahibi, are you sure that not all the accounts configured on your "nexcloud app" all already configured on your "nextcloud-talk android app" ? If all the accounts are already configured, the "import account from app" it's not shown on "nextcloud-talk android app" installed from Github nor Google Play Store. Can you confirm this ?**

 I just tested it now, on a Xiaomi terminal with v14.2.0 installed from Google Play, and a Xiaomi terminal (mine) with v15.0.0-RC5 installed from Github. I worked like I describe above.

To confirm all the process, I've tried the "import account from function" with the Xiaomi terminal with "nextcloud app" and "nextcloud talk android app v14.2.0" installed with Google Play with a new created test-account. All have worked correctly*.  Well the issue related on #743 happens.

**Comment by migulen** [comment]
>Yesterday I upgraded my nextcloud server to v23.0.10, Spreed (Talk) to v13.0.9. Today I've been using v15.0.0-RC4 nextcloud-talk and "account hiding" didn't happened.

>I upgraded to v15.0.0-RC5 to just now... and will continue testing tomorrow.

**By the way, and the origin of this issue, since Wednesday (4 days), and the upgrades indicated above, 0 "accounts hiding"/"server gone" have happened  to me :-).**  

Why ? I don't know...  @jakobroehrl have you upgraded to v15.0.0-RC4 o 5, and are lucky like me ?

**Comment by mahibi** [comment]
> just checked: the hidden "import account from nextcloud app" option is not related to versions! it only works when apk is manually installed from github. via play store it fails. will have a closer look on monday..

i was wrong here indeed. it works with playstore as well. It only fails in debug mode when developing, because then the apk is not signed with the same signature like the files app is.

Anyway also with imported accounts from the files app i was not able to reproduce the main issue yet.

**Comment by jakobroehrl** [comment]
> Why ? I don't know... @jakobroehrl have you upgraded to v15.0.0-RC4 o 5, and are lucky like me ?

I think yes. I have not had this problem for days

**Comment by mahibi** [comment]
that's strange :eyes: 
if the issue occurs again just ping me here. Any screenshots or screenvideos would be helpful maybe.. 

sidenote: when looking at the server selection code i simplified the logic, see https://github.com/nextcloud/talk-android/pull/2518. But this should but change any behaviour, just refactoring..

**Comment by JimmyKater** [comment]
I'm gonna leave my experiences here as detailed as it could get..

Until some days ago (like 2 or 3) I had two Talk-accounts working with Talk-app (android) installed from F-Droid. I could switch perfectly between both of them, read & write messages with no problems. Only notifications didn't work. 
By thinking about it I remembered that at some point someone (on the forum) said that there could be a notificationproblem with apps installed from F-Droid.
And so I deleted my F-Droid-app and installed the one from G00gle playstore (v15.0.1). 
As said before that happened 2 or 3 days ago. 
Then I can't remember exactly if I registered both accounts again or only one. I think I registered both but I'm not 100% sure. 
The notifications worked and I was all happy.
 
Yesterday late afternoon I discovered that someone from 2nd account wrote something on chat, I got notified. And could read content from the notification window. But when I tried to enter the chat I got transferred to my first account. 
Then I tried several times re-registering my 2nd account... which apparently was successful but I never could access any chat and was thrown back to my first account immediately.
By checking settings 2nd account wasn't showing up on App.
Though I keep receiving notifications for it. 

Funny sidenode is: 1st account is on my instance. 2nd account is running on cloud.nextcloud.com 

Android 12, Nokia TA1243

if you'll need further details, just feel free to ask.

**Comment by migulen** [comment]
**Hello @mahibi, it continues happening**:

29 times, since 27/09/2022.

13 times, since last 24 days.

It's not related to be low space in the mobile. I have it with 500MB of free space... and freed 4 GB more and continues happening. I though that could be related to saving something on the memory of the mobile, and another process killing the saving operation of data.

(In my case) It's something related to change from network (could be wifi to other wifi, or mobile to wifi, or wifi to mobile, or loosing connection, in short... close/change connection or change IP of mobile)  when I'm doing some operation with Nextcloud Talk. "Operation" could be: changing between accounts, access to rooms, change from rooms, sending messages, etc.

**But today... something different has happened. The hidden account has returned the same way it wents**. Before I was going to re-add the hidden account, I changed from one wifi to another... and after that, I saw that the hidden account returned by itself. 

It's something cutting and overlapping the process of "changing" account. Why it happens without being ALWAYS in the process of changing between accounts... I don't know.

Nowadays scenario:
Nextcloud Server: v24.0.7  (php 7.4)
Nextcloud Spreed app:  v14.0.6
Nextcloud Talk android app: v15.0.1

By the way.... THANKS for the enormous improvements since V23 Server to v24 Server (Spreed, Server, Talk-app android) in a lot of aspects. 

https://github.com/nextcloud/talk-android/issues/743 continues happening.

**Comment by mahibi** [comment]
ok i just played around a lot and finally i was able to reproduce... now debugging...

**Comment by mahibi** [comment]
@jakobroehrl @JimmyKater @migulen 
can you try out the apk from https://github.com/nextcloud/talk-android/pull/2581#issuecomment-1320064606 and let me know if it's fixed?

**Comment by ASerbinski** [comment]
@mahibi ; Since https://github.com/nextcloud/talk-android/pull/2581#issuecomment-1320064606 has been moved to milestone 15.1.0, should this issue not also be moved there so as not to block release of 15.0.2?

**Comment by mahibi** [comment]
i put https://github.com/nextcloud/talk-android/pull/2581 for 15.0.2 again. We will discuss this today if it gets merged or not. we plan to release 15.0.2 RC today

**Comment by migulen** [comment]
Today, another mystery...  you remember this: "But today... something different has happened. The hidden account has returned the same way it wents. " from (https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1314373241)

Today  my 2 real accounts have been duplicated with v15.0.1. I've a screenshot of it, the account selector on the app, shows 4 accounts (A and A', B and B'). I've deleted each duplicate instance of the accounts (A' and B'), then the original accounts continues working correctly. :-/

There is a little mesh with the "selected account", but I think it isn't a problem caused (only) by the account selector...

**Comment by XueSheng-GIT** [comment]
@AndyScherzinger I'm on talk-android 16.0.0 rc2 and this issue appeared for me for the first time (account not visible in the account switcher). By adding another account, it reappeared again!
Is it possible that this is a regression?

**Comment by mahibi** [comment]
> @AndyScherzinger I'm on talk-android 16.0.0 rc2 and this issue appeared for me for the first time (account not visible in the account switcher). By adding another account, it reappeared again! Is it possible that this is a regression?

thanks for reporting @XueSheng-GIT , you're the first to report this in a while. Does anyone else encounter this problem again?

**Comment by migulen** [comment]
Hi @mahibi , **not me**. I'm using v16.0.0-RC2 since it get published. 

@mahibi , I know it isn't related to this issue... but:

 why it's forbiden in this version check text of a  "different room" if you are on a "call or videocall" ? It was nice the posibility of look for info from other "rooms" at the same time you are "talking with someone else".

**Comment by TwizzyDizzy** [comment]
Still seeing this on latest NC Talk Android and latest NC Server version. That being said: still didn't manage to reliably reproduce the issue :(

Cheers
Thomas

**Comment by aluaces** [comment]
Some additional info:

* The issue seems very independent from the version of the android app and the server, since it is happening since several releases ago.
* It's not related to the device: in the meantime, I have changed my phone (different brand and android version) and it happens now as well.
* I have only two accounts in different servers, but with different usernames, so I guess this rules out a possible username mismatch.
* After an account is *forgotten*, any attempt to login again leads to an authentication loop: I can see in the server that several *app passwords* are created in each iteration.  I have to delete all the application data and login in both accounts again.
* Happens as well in both google and f-droid versions.

**Comment by migulen** [comment]
@aluaces , nice tips.

@mahibi , It continue happening, even with 18.x.x, but it's very uncommon.

**Comment by mahibi** [comment]
Thanks for the infos.
I'm quite busy with other things but definitely have this issue in mind. Will have a look whenever time allows.

**Comment by migulen** [comment]
@mahibi  with versión v19.0.0 doesn't happen anytime for now.

**Comment by mahibi** [comment]
Thanks to let me know @migulen 
Can you confirm this @jakobroehrl ?

**Comment by TwizzyDizzy** [comment]
The last time I tried to have a second account in the app, I usually wasn't even able to successfully to add a second account.

This has changed. I was able to add a second account and indeed, it hasn't disappeared yet. Just now, I thought it happened again in the account chooses, but after 1 or 2 seconds, the second account showed.

So I think it's safe to say that there was improvement that might warrant a close. One could re-open, once somebody has actually seen this happening again on 19.x+. I'll certainly report back, should that happen.

Cheers
Thomas

**Comment by aluaces** [comment]
I currently have 19.0.0 installed, and one of my accounts disappeared before the update, I think with 18.1.0.

If I try to login now to the lost account again, it keeps restarting the authorization phase.  I have tried using `adb log`, but I'm not sure what I should be looking for.

**Comment by jakobroehrl** [comment]
> Thanks to let me know @migulen Can you confirm this @jakobroehrl ?

For me, it works very good, too.

**Comment by mahibi** [comment]
thanks to let me know, i will close the issue.

> I currently have 19.0.0 installed, and one of my accounts disappeared before the update, I think with 18.1.0.
> 
> If I try to login now to the lost account again, it keeps restarting the authorization phase. I have tried using `adb log`, but I'm not sure what I should be looking for.

This sounds like a different issue. Does that happen for all accounts on this server? Could you create a test account for me on the server where it fails? Just send it to marcel dot hibbe at nextcloud dot com
Otherwise, could you create a new github issue?

**Comment by aluaces** [comment]
> This sounds like a different issue. Does that happen for all accounts on this server? Could you create a test account for me on the server where it fails? Just send it to marcel dot hibbe at nextcloud dot com Otherwise, could you create a new github issue?

I think it is the same issue.  It just happened that this time when one of the accounts disappeared, I let it that way to see if newer updates of the app solved the issue, and to try to debug a bit with `adb log`.

I'm resetting the app and configuring my two accounts again (because it happens randomly with different servers and different versions of NC) and see what happens in the future.

The problem is that this bug is not showing immediately —sometimes can take weeks until it happens.

**Comment by TwizzyDizzy** [comment]
> So I think it's safe to say that there was improvement that might warrant a close. One could re-open, once somebody has actually seen this happening again on 19.x+. I'll certainly report back, should that happen.

I'm afraid it happened again. (Android) App version `19.0.1`, server version `29.0.1`. My above comment was three weeks ago, that's how long it took.

Cheers
Thomas

**Comment by migulen** [comment]
Not happened to me since v19.x.x . The accounts seems to refresh everytime I connect (open the app) now. @jakobroehrl , you too ?

**Comment by migulen** [comment]
@jakobroehrl @mahibi @TwizzyDizzy. Not happened anymore for me (talk versions 19.1.0 or 20.0.0).

I think that it could be closed.

**Comment by aluaces** [comment]
It just happened to me last week with 19.0.1

Nevertheless, instead of just disappearing, it's my impression that now it tries harder to connect, since sometimes you can see the icon of the other account disappearing and appearing again.

My theory is that it has to do with faulty connections; the app might try to connect to every account, and if it is not able to do so, it deletes or blocks that account.

I think I saw sometimes ago something about a "rejected invitation" one of those times, but I had no time for looking in the sources for that term.

**Comment by TwizzyDizzy** [comment]
> Nevertheless, instead of just disappearing, it's my impression that now it tries harder to connect, since sometimes you can see the icon of the other account disappearing and appearing again.

I pointed this out somewhere above already: indeed, even if you do not see it in the app anymore, the requests still happen in the background, verified this on my server.

In any case: I just reset the app, added my 2 accounts and will check from time to time. Will report, should it happen again.

Cheers
Thomas

**Comment by aluaces** [comment]
Sorry, but this happened to me *twice* with `20.0.2` and two NC servers with versions `27` and `30`.

One time one of them disappeared, and the other time it was the other server the one disappearing.

**Comment by migulen** [comment]
@aluaces, @TwizzyDizzy , the lost account "never" reappears  ?

  Like I said on Sept 16, I doesn't happened to me more. I'm not sure, but in my case, the account chooser seems to try to renew/refresh the configured accounts list everytime it's activated, and acomplish it.  Could be your hidden accounts are not happening during a mobile conectivity problem ?   Mine always finish  reappearing.

**Comment by TwizzyDizzy** [comment]
> but in my case, the account chooser seems to try to renew/refresh the configured accounts list everytime it's activated

I agree with that observation. The reason I can tell is, because the second Nextcloud Account I have in there is on an NC instance on rather limited hardware, so it usually takes a bit longer to load.

> Could be your hidden accounts are not happening during a mobile conectivity problem

I'd say "rather no", unless as **singular occurrence of a failed connection** leads to a **permanent issue** in the app. My guess is that this is not the case, because if it were the case, we would very likely see far more reports of this issue.

> Mine always finish reappearing.

In my case, once an account was gone from the account list, in my case it **never** reappeared.

All that being said: since my last post on Sep 16th I had no issue. App version `20.0.2`, two 30.x servers (`30.0.2` as of today).

Cheers
Thomas

**Comment by migulen** [comment]
@TwizzyDizzy 

"I agree with that observation. The reason I can tell is, because the second Nextcloud Account I have in there is on an NC instance on rather limited hardware, so it usually takes a bit longer to load until showing up."

I think this slowness could be the problem and could be that this turns on a "permanent issue" on some cases. I don't know. I think that the new protocol from @mahibi since v19.1.0 (or v20.x.x) for checking the accounts it's more accurated... but can't ensure.   

---------------------------------------------------

I think the situation has improved a lot since 19.1.0 and up.  Like you said, it hapened with 19.0.1, but not since 20.0.2.   @aluaces was who has the problem with 20.0.2. Better to wait for him.

**Comment by TwizzyDizzy** [comment]
> I think this slowness could be the problem and could be that this turns on a "permanent issue" on some cases. I don't know. I think that the new protocol from @mahibi since v19.1.0 (or v20.x.x) for checking the accounts it's more accurated... but can't ensure.

I just made this point to kinda confirm your point (that the app refreshes the account list when opening the account chooser), not to imply that it's always the slower one disappearing.For now, it's like you say:

> it hapened with 19.0.1, but not since 20.0.2. @aluaces was who has the problem with 20.0.2. Better to wait for him.

Rest assured though, that I will reply, should it happen again.

Cheers
Thomas

**Comment by aluaces** [comment]
I have seen as well that recent versions try *harder* to connect, because sometimes it takes a bit for the icon of an account to show up.

But once it is not appearing in less than a minute, it is gone **forever**.

It happened again after my report, this time losing the account of the *supposedly faster server*.  Actually the connections are lost randomly.

From the outside, it seems like some lock inside the app, since once a server connection is lost, you cannot restore it unless you clear all the data and start over.

Is there any way of looking at the app database to see what happens before and after? Why can a connection disappear if it is not explicitly deleted by the user?

**Comment by aluaces** [comment]
Since several versions ago, this problem is _not_ present for me anymore. Now maybe an account is not shown for the first seconds (likely because of a slow response of the server), but then it is recovered.

I have not lost any account configuration since, so for me this bug is resolved.

**Comment by mahibi** [comment]
I guess it is about https://github.com/nextcloud/talk-android/issues/5095 which should have been solved by https://github.com/nextcloud/talk-android/pull/5227 (which is not yet released)
But unfortunately users reported that it's also not fixed with this PR.

So regardless of the version, neither "loosing" an account nor displaying it with delay is okay. It should be shown immediately. @sowjanyakch will have another look

**Comment by mahibi** [comment]
Do the accounts have the same name? If yes, it should be fixed with https://github.com/nextcloud/talk-android/pull/5588

**Comment by aluaces** [comment]
At least the _display name_ is the same, but I'm not sure about the account name since in one of the servers I'm not the admin and I don't know how to look for it as a regular user (I'm using my email address for login in that server).

**Comment by mahibi** [comment]
I think the bug was meanwhile re-introduced bug not released and https://github.com/nextcloud/talk-android/pull/5588 is just the fix for the re-introdcued bug. 
If it's about same names it should be fixed in 22.1.0 RC1

**Comment by migulen** [comment]
@mahibi 

Same name and "username", yes. 

https://github.com/nextcloud/talk-android/issues/2446#issuecomment-1265854841

**Comment by aluaces** [comment]
I have checked that in my case, the display name is the same, but the user name is different: in one case it is a login name, and in the other the email I used to register.

**Comment by mahibi** [comment]
should be fixed with 22.1.0 which will be released soon. Please let me know if it's fixed then.

**Comment by migulen** [comment]
hi @mahibi , I'm using 22.1.0-RC1 and "Accounts disappear" isn't happening for now, but in one of my servers I get "duplicated account" option in the account selector. I will inform when 22.1.0 get release. 

My nextcloud servers are too much outdated so don't take it like "real  situation", sorry.

**Comment by mahibi** [comment]
> but in one of my servers I get "duplicated account" option in the account selector. 

sounds like a different issue,  so maybe https://github.com/nextcloud/talk-android/issues/4499

**Comment by migulen** [comment]
@mahibi , yes, just like that.

**Comment by mahibi** [comment]
I will close the issue. Please reopen if it happens with >= 22.1.0
