### ISSUE TITLE
Pixel 3a Android 10 frequent crash on app v7.0.2 launch and attempted use

### ISSUE THREAD

**Issue by bobreidx** [nextcloud/talk-android#648]
After installing version 7.0.2, the Android app still crashes on initial launch, and then crashes intermittently when accessing a conversation. I was only able to post to a conversation once before another app crash. Also, the app now has to pull the entire message thread before input is allowed (similar to the web client). Before the app would cache the thread locally.

I re-installed the app to test, and the issues persist. I have uninstalled for now.

**Comment by gerroon** [comment]
I have the same issue, the previous version worked fine. Can you please tell me how I can get the logs?

I am using it on LIneageOS 14.1

**Comment by shafer** [comment]
I'm experiencing the same problem on my Nokia 7.1 and Nextcloud Talk for Android v7.0.2 talking to a server version of 16.0.5 and previously it was 16.0.4, both exhibit the same problem.

For one crash I did submit feedback instead of closing the app.

Happy to collect other logs with pointers.

**Comment by Winschu** [comment]
I've had some similar issues with Android 10 on a Pixel 2 XL. I will post a log here at a later point of time.

**Comment by ScorpSoul** [comment]
Galaxy S8 having the same issue. Keeps crashing even after reinstall and data cleanup

**Comment by gerroon** [comment]
I went back to 6 beta 3 (which I had a back up of) and the crashes stopped.

**Comment by mario** [comment]
Fixed release on Monday

**Comment by shgysk8zer0** [comment]
Another user experiencing this issue, and I see that a fix is coming on Monday.

Just curious about 2 things:
1. A reply to someone who reported this in a review on Play Store mentioned setting up TURN server. Is that related?
2. Any issues experienced on iOS?

**Comment by mario** [comment]
Turn has nothing to do with this :)

**Comment by yostral** [comment]
Nextcloud Talk updated today, but still crashing randomly. Less often, but still.

How to get more logs?

**Comment by mario** [comment]
Sorry about all the issues folks. Let me know when you test v7.0.5 that should be out later today.

**Comment by yostral** [comment]
No worries, keep doing your great work! I will let you know how the 7.0.5 will behave.

**Comment by mario** [comment]
You could also speed it up by installing it from a link:

https://github.com/nextcloud/talk-android/releases/download/v7.0.5/nextcloud-talk.apk

Same signature as the GPlay one.

**Comment by yostral** [comment]
It looks ok for the moment, no crash! Thank you! 

And when you load a thread, it doesn't scroll from the top anymore!  That is good :).

**Comment by AaronADev** [comment]
@mario Good job and thanks for the work on this. Issue appears to be cleared up from my end as well.

**Comment by mario** [comment]
Thanks for the feedback and sorry for the issues!

**Comment by bobreidx** [comment]
Version 7.0.5 works really well. Thanks, Mario!!!
