### ISSUE TITLE
STUN / TURN server: No Audio / Video transmission (but using a mobile browser works!)

### ISSUE THREAD

**Issue by t-lo** [nextcloud/talk-android#934]
* Nextcloud version 19.0.4
* Android App version 8.0.10

I'm running a STUN/TURN server to route audio/video traffic through NATs (local LAN). STUN server and nextcloud server are on the internet w/ public IPs.

The following scenario does not work:
* Nexcloud app on Android phone with audio / video transmission - when initiating or receiving a videcall, the screen remains black. The receiver side does not receive any video / audio either.

The following scenario works:
* Using Chrome or Firefox on the Android phone and initiating or receiving a videocall from the browser. Video and audio are both sent and received, on both ends.

There appears to be an issue with STUN handling in the Talk App.

**Comment by tobiasKaminsky** [comment]
@nickvergessen do you have any hint you can give me, where/how to debug this?

**Comment by tobiasKaminsky** [comment]
@t-lo can you try if it makes a difference if
- android starts the call, then web join
- web starts the call, android joins
- web starts a call, android joins, if still black: leave on android and join again

**Comment by t-lo** [comment]
Thanks for getting back so quickly, Tobias.

Test scenario: laptop in private (NATed) wifi, mobile phone connected to LTS, STUN/TURN and Nextcloud server have public IP.

Test 1: android starts the call, then web join
Android talk app initiates call, displays black screen and tiny self video on the upper right. The call is reported successfully in the nextcloud talk chat. Laptop joins the call via web. Web displays Android user's icon in full screen with tiny self-image on upper right. No audio or video is transmitted within 120 seconds; Android screen stays black.

Test 2: Web starts the call, then android joins
Web app starts the call,  Android user's icon is displayed in full screen with tiny self video on the upper right. The call is reported successfully in the nextcloud talk chat, but Android app does not "ring" and does not emit a notification, just a message is displayed in the chat. Android joins the call. Android screen shows black, with tiny self video on the upper right. No video or audio is transmitted within 120s.

Test 3: (Continuing from test 2 above) Android leaves the call, then re-joins
Android app leaves the call. Leave is reported successfully in the Talk chat. Web displays a black screen now, with tiny self video on the upper right. Android rejoins the call. Join is reported successfully in the talk chat. Android app screen turns black with tiny self video on upper right. Web displays Android user icon maximised, with tiny self video on upper right. No video or audio transmission within 120s.

To make sure it's not a connection issue I also tested both scenario 1 and 2 with mobile browsers - Firefox and Chrome. Both browsers were able to successfully initiate a video call as well as join a video call initiated by the laptop.

Please let me know if there's anything I can do / provide to help debugging this issue (log files etc.).

**Comment by mobymolly** [comment]
May be related to #936 but in that issue, Android users **can transmit but not receive** video.

**Comment by tobiasKaminsky** [comment]
@nickvergessen so this seems different than what I fixed last time with "outdated" session id…

**Comment by t-lo** [comment]
Is there anything I can do to help / to provide more information (since the issue is labelled with "needs info")? Will happily side-load a development apk of nextcloud-talk and re-run the tests if that helps.

**Comment by tobiasKaminsky** [comment]
Thanks for the offer, @t-lo

@danxuliu as you are also very experienced with all Talk stun/turn/etc, do you have an idea how we can debug this?

**Comment by t-lo** [comment]
@tobiasKaminsky @danxuliu Issue still "needs info" according to label. I'm more than willing to help with providing the info needed 
- I'm running a STUN/TURN server (coturn) and would love to provide logs if that helps
- Also, happy to side-load a debug version of the Talk app to provide logs etc.
How can I help providing the info needed?

**Comment by Arusina** [comment]
Maybe my problem is related to this one. When using the app, the "standard" app interface does not open but the website interface (see picture). I suspect a wrong configuration of the TURN / STUN server. 
Is your Nextcloud server behind a reverse proxy?
![grafik](https://user-images.githubusercontent.com/45320603/103404650-ae632000-4b54-11eb-816d-0b524998f004.png)

**Comment by t-lo** [comment]
OK so "just waiting" helped - with Nextcloud 20.0.9 and the Android talk app v11.1.0 the issue disappeared. Not sure what fixed it, but not sure I want to know, either :)

Closing this, thanks!
